import type { NextPage } from 'next';
import Head from 'next/head';
import { useContext, useEffect, useState } from 'react';
import axios from 'axios';
import Link from 'next/link';

import * as Styled from '../styles';
import Landing from '../components/Landing/index';
import { PostContext } from '../context/PostContext';
import { bgColor } from '../styles/utilities';

interface Values {
  value: [];
}

const Home: NextPage<Values> = ({ value }) => {
  const { addingPosts } = useContext(PostContext);
  const [hover, setHover] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);

  useEffect(() => {
    if (!value) setLoading(true);
    if (value) {
      addingPosts(value);
      setLoading(false);
    }
  }, [value, addingPosts]);
  console.log(value)
  return (
    <>
      <Head>
        <title>Gabriel Barreto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Styled.Container>
        <Link href="https://www.ghbarreto.dev" passHref>
          <Styled.Button
            onMouseEnter={() => setHover(true)}
            onMouseLeave={() => setHover(false)}
            bgColor={hover ? bgColor : 'transparent'}
            fontSize={'26px'}
            paddingLeft={'250px'}
            margin={'-100px'}
            color={hover ? 'white' : bgColor}
          >
            <Styled.Tags fontSize={'29px'}>《&#123;</Styled.Tags>Portfolio
            <Styled.Tags fontSize={'29px'}>&#125;</Styled.Tags>
          </Styled.Button>
        </Link>
        <Styled.Component>
          {loading && <h3>Loading...</h3>}
          <Landing />
        </Styled.Component>
      </Styled.Container>
    </>
  );
};

Home.getInitialProps = async ({ req }) => {
  let protocol = 'https://';
  let host = req ? req.headers.host : window.location.hostname;

  if (host && host.indexOf('localhost') > -1) {
    protocol = 'http://';
  }

  // http://localhost:3000/api/fetch_posts
  // ${protocol}${host}/api/fetch_posts`
  try {
    const { data } = await axios.get(`${protocol}${host}/api/fetch_posts`);
    return {
      value: data,
    };
  } catch (err) {
    return {
      value: { err },
    };
  }
};

export default Home;
