import type { NextPage } from 'next';
import Head from 'next/head';
import { useContext, useEffect } from 'react';

import * as Styled from '../styles';
import Landing from '../components/Landing/index';
import { PostContext } from '../context/PostContext';

interface Values {
  value: []
}

const Home: NextPage<Values> = ({ value }) => {
  const { addingPosts } = useContext(PostContext);

  useEffect(() => {
    addingPosts(value);
  }, [value, addingPosts]);

  return (
    <>
      <Head>
        <title>Gabriel Barreto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Styled.Container>
        <Styled.Button
          hoverBg={'#222222'}
          fontSize={'26px'}
          paddingLeft={'120px'}
          margin={'-100px'}
        >
          <Styled.Tags fontSize={'29px'}>《&#123;</Styled.Tags>Portfolio
          <Styled.Tags fontSize={'29px'}>&#125;</Styled.Tags>
        </Styled.Button>
        <Styled.Component>
          <Landing />
        </Styled.Component>
      </Styled.Container>
    </>
  );
};

Home.getInitialProps = async () => {
  const res = await fetch('http://localhost:3001/api/fetch_posts');

  return {
    value: await res.json(),
  };
};

export default Home;
